### ISSUE TITLE
Stardrop refuses to install "new mods" from nexus but appears to be able to update mods that i had previously installed. 

### ISSUE THREAD

**Issue by BenTGI** [Floogen/Stardrop#157]
[log.txt](https://github.com/Floogen/Stardrop/files/14014385/log.txt)
Stardrop Log

https://smapi.io/log/407197521ff1412ea37c8e91805e6d7f
Smapi Log 

Stardrop refuses to install "new mods" from nexus saying that it can't  but appears to be able to update mods that i had previously installed though it does still come up with the same error message as it would with new mods on some of the updates. it appears to be random whether it will appear or not per mod but it always appears on the same mod. 
![error message](https://github.com/Floogen/Stardrop/assets/126521168/a5ac6690-9f90-4b47-9c33-e1e5c9344d2c)

**Comment by Adda0** [comment]
Hello. Relevant Stardrop log output:
```
[22/01/2024 18:43:52][Debug][MainWindow.AddMods: Line 1946] Install path for mod Lnh.SimpleFarm2:D:\Users\Benjamin Willis\Documents\Stardew Valley - 1.5.6\Mods\Stardrop Installed Mods
[22/01/2024 18:43:52][Warning][MainWindow.AddMods: Line 2000] Failed to unzip the file C:\Users\Benjamin Willis\AppData\Roaming\Stardrop\Data\Nexus\Lnh's Simple Farm2 due to the following error: System.UnauthorizedAccessException: Access to the path 'D:\Users\Benjamin Willis\Documents\Stardew Valley - 1.5.6\Mods\Stardrop Installed Mods\Lnh's Simple Farm2' is denied.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Stardrop.Views.MainWindow.AddMods(String[] filePaths)
...
[22/01/2024 18:42:36][Warning][MainWindow.AddMods: Line 2000] Failed to unzip the file C:\Users\Benjamin Willis\AppData\Roaming\Stardrop\Data\Nexus\Alchemist's Valley due to the following error: System.UnauthorizedAccessException: Access to the path 'D:\Users\Benjamin Willis\Documents\Stardew Valley - 1.5.6\Mods\Stardrop Installed Mods\Alchemist's Valley\[BF] Potion Effects' is denied.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Stardrop.Views.MainWindow.AddMods(String[] filePaths)
```
According to this, you do not have access rights to create a directory in the installed mods path. I cannot reproduce this issue on Linux with the newest Stardrop version. I do not have any Windows machine to try it there, however.

Does this issue appear with all new mods, and especially with mods which does not contain an apostrophe in the name, or just a select few new mods?

Also, if you want, you could try the following actions to further investigate. Just to be sure, could you move the mod archive files from `AppData/Roaming` directory somewhere under your user documents, for example? And try to install the mods from there. Afterwards, try to go to Stardrop settings and change the Stardrop installed mods path to something else, under your documents for example as well. And try to install the mod (from the place where you put the archive files, as described above) again.

What I suspect is that there is a problem with handling apostrophes in the folder names. That might lead to such access right failures. Either at Windows level, or Stardrop level on Windows.

**Comment by BenTGI** [comment]
setting the Executable as run as admin worked. 

i have never needed to do that in the past...5 months or so that i have had Stardrop configured in this way.

**Comment by Sweatytitties** [comment]
im currently having the same issue even if I open Stardrop as admin
![image_2024-03-25_160148078](https://github.com/Floogen/Stardrop/assets/164840163/a3168440-666c-4386-a929-81fef52d7a99)
Stardrop log: 
[log.txt](https://github.com/Floogen/Stardrop/files/14739033/log.txt)

**Comment by Sweatytitties** [comment]
im currently having the same issue even if I open Stardrop as admin
![image](https://github.com/Floogen/Stardrop/assets/164840163/a6edde81-5ad3-494f-9584-88d1fa5671b0)
Stardrop log: 
[log.txt](https://github.com/Floogen/Stardrop/files/14739033/log.txt)
