### ISSUE TITLE
Renaming StardewModdingAPI.exe prevents Stardrop from being used (Xbox Gamepass)

### ISSUE THREAD

**Issue by Verciv** [Floogen/Stardrop#63]
The Stardew Valley wiki says to rename _StardewModdingAPI.exe_ to _Stardew Valley.exe_, but Stardrop does not support this method. It only accepts the file path if SMAPI is named exactly _StardewModdingAPI.exe_.

Below is an image of how SMAPI should be named, according to the wiki:
![image](https://user-images.githubusercontent.com/78374482/157578776-a83c4875-8a0e-49cf-aea7-77a755f8dc11.png)

Additionally, I get this error when I try to show the file path to Stardrop:
![image](https://user-images.githubusercontent.com/78374482/157579021-554bd4ac-3808-4a3f-b036-5dfabf545590.png)

![image](https://user-images.githubusercontent.com/78374482/157578985-636b0e6b-aeae-4127-be70-915a1a08d40b.png)

(I could just launch SMAPI without renaming it, but this disables achievements and multiplayer, and I feel like this could be mitigated). 
Thank you for reading, and while this bug isn't too serious, it kind of prevents Gamepass owners from using Stardrop on the same capacity as someone that owns the game on Steam.

Edit: Deleted log.txt, will just paste it outright.

**Comment by Verciv** [comment]
`txt
[3/9/2022 6:57:11 PM][Debug][Program.Main: Line 53] 
-- Startup Data --
Time: 3/9/2022
OS: Microsoft Windows 10.0.19044
Settings Directory: C:\Users\%USERPROFILE%\AppData\Roaming\Stardrop\Data
Active Directory: C:\Program Files\Stardrop
Version: 1.0.0-beta.27
----------------------

[3/9/2022 6:57:11 PM][Debug][Program.Main: Line 54] Started with the following arguments: 
[3/9/2022 6:57:12 PM][Debug][Translation.LoadTranslations: Line 119] Loaded language de
[3/9/2022 6:57:12 PM][Debug][Translation.LoadTranslations: Line 119] Loaded language default
[3/9/2022 6:57:12 PM][Debug][Translation.LoadTranslations: Line 119] Loaded language es
[3/9/2022 6:57:12 PM][Debug][Translation.LoadTranslations: Line 119] Loaded language fr
[3/9/2022 6:57:12 PM][Debug][Translation.LoadTranslations: Line 119] Loaded language it
[3/9/2022 6:57:12 PM][Debug][Translation.LoadTranslations: Line 119] Loaded language pt
[3/9/2022 6:57:12 PM][Debug][Translation.LoadTranslations: Line 119] Loaded language ru
[3/9/2022 6:57:12 PM][Debug][Translation.LoadTranslations: Line 119] Loaded language th
[3/9/2022 6:57:12 PM][Debug][Translation.LoadTranslations: Line 119] Loaded language tr
[3/9/2022 6:57:12 PM][Debug][Translation.LoadTranslations: Line 119] Loaded language uk
[3/9/2022 6:57:12 PM][Debug][Translation.LoadTranslations: Line 119] Loaded language zh
[OpenGL] Unable to initialize EGL-based rendering: 'System.DllNotFoundException: Dll was not found.
   at Avalonia.OpenGL.Angle.AngleEglInterface.EGL_GetProcAddress(String proc)
   at Avalonia.OpenGL.Angle.AngleEglInterface.LoadAngle()
   at Avalonia.OpenGL.Angle.AngleEglInterface..ctor()
   at Avalonia.OpenGL.Angle.AngleWin32EglDisplay..ctor()
   at Avalonia.Win32.Win32GlManager.<>c.<Initialize>b__0_1()
   at Avalonia.OpenGL.Egl.EglPlatformOpenGlInterface.TryCreate(Func`1 displayFactory)'
LogHost: Initializing to normal mode (.cctor)
[3/9/2022 6:57:15 PM][Debug][App.Initialize: Line 29] Loaded theme Dark
[3/9/2022 6:57:16 PM][Debug][App.Initialize: Line 29] Loaded theme Light
[3/9/2022 6:57:16 PM][Debug][App.Initialize: Line 29] Loaded theme Solarized-Lite
[3/9/2022 6:57:16 PM][Debug][App.Initialize: Line 29] Loaded theme Stardrop
[Binding] Error in binding to 'Avalonia.Controls.NativeMenuItem'.'Command': 'Null value in expression '{empty}' at ''.' (NativeMenuItem #60348264)
[Binding] Error in binding to 'Avalonia.Controls.DataGridTemplateColumn'.'IsVisible': 'Null value in expression '{empty}' at ''.' (DataGridTemplateColumn #54330728)
[3/9/2022 6:57:18 PM][Debug][MainWindow.CheckForModUpdates: Line 1011] Attempting to check for mod updates via cache
[3/9/2022 6:57:18 PM][Alert][MainWindow.CheckForModUpdates: Line 1183] Failed to get mod updates via smapi.io: System.IO.FileNotFoundException: C:\XboxGames\Stardew Valley\Content\StardewModdingAPI.exe
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at Stardrop.Views.MainWindow.CheckForModUpdates(List`1 mods, Boolean useCache, Boolean probe, Boolean skipCacheCheck)
[3/9/2022 6:57:40 PM][Debug][SettingsWindow..ctor: Line 54] Loaded theme Dark
[3/9/2022 6:57:40 PM][Debug][SettingsWindow..ctor: Line 54] Loaded theme Light
[3/9/2022 6:57:40 PM][Debug][SettingsWindow..ctor: Line 54] Loaded theme Solarized-Lite
[3/9/2022 6:57:40 PM][Debug][SettingsWindow..ctor: Line 54] Loaded theme Stardrop
`

**Comment by Verciv** [comment]
`[3/9/2022 6:57:11 PM][Debug][Program.Main: Line 53] 
-- Startup Data --
Time: 3/9/2022
OS: Microsoft Windows 10.0.19044
Settings Directory: C:\Users\%USERPROFILE%\AppData\Roaming\Stardrop\Data
Active Directory: C:\Program Files\Stardrop
Version: 1.0.0-beta.27
----------------------

[3/9/2022 6:57:11 PM][Debug][Program.Main: Line 54] Started with the following arguments: 
[3/9/2022 6:57:12 PM][Debug][Translation.LoadTranslations: Line 119] Loaded language de
[3/9/2022 6:57:12 PM][Debug][Translation.LoadTranslations: Line 119] Loaded language default
[3/9/2022 6:57:12 PM][Debug][Translation.LoadTranslations: Line 119] Loaded language es
[3/9/2022 6:57:12 PM][Debug][Translation.LoadTranslations: Line 119] Loaded language fr
[3/9/2022 6:57:12 PM][Debug][Translation.LoadTranslations: Line 119] Loaded language it
[3/9/2022 6:57:12 PM][Debug][Translation.LoadTranslations: Line 119] Loaded language pt
[3/9/2022 6:57:12 PM][Debug][Translation.LoadTranslations: Line 119] Loaded language ru
[3/9/2022 6:57:12 PM][Debug][Translation.LoadTranslations: Line 119] Loaded language th
[3/9/2022 6:57:12 PM][Debug][Translation.LoadTranslations: Line 119] Loaded language tr
[3/9/2022 6:57:12 PM][Debug][Translation.LoadTranslations: Line 119] Loaded language uk
[3/9/2022 6:57:12 PM][Debug][Translation.LoadTranslations: Line 119] Loaded language zh
[OpenGL] Unable to initialize EGL-based rendering: 'System.DllNotFoundException: Dll was not found.
   at Avalonia.OpenGL.Angle.AngleEglInterface.EGL_GetProcAddress(String proc)
   at Avalonia.OpenGL.Angle.AngleEglInterface.LoadAngle()
   at Avalonia.OpenGL.Angle.AngleEglInterface..ctor()
   at Avalonia.OpenGL.Angle.AngleWin32EglDisplay..ctor()
   at Avalonia.Win32.Win32GlManager.<>c.<Initialize>b__0_1()
   at Avalonia.OpenGL.Egl.EglPlatformOpenGlInterface.TryCreate(Func`1 displayFactory)'
LogHost: Initializing to normal mode (.cctor)
[3/9/2022 6:57:15 PM][Debug][App.Initialize: Line 29] Loaded theme Dark
[3/9/2022 6:57:16 PM][Debug][App.Initialize: Line 29] Loaded theme Light
[3/9/2022 6:57:16 PM][Debug][App.Initialize: Line 29] Loaded theme Solarized-Lite
[3/9/2022 6:57:16 PM][Debug][App.Initialize: Line 29] Loaded theme Stardrop
[Binding] Error in binding to 'Avalonia.Controls.NativeMenuItem'.'Command': 'Null value in expression '{empty}' at ''.' (NativeMenuItem #60348264)
[Binding] Error in binding to 'Avalonia.Controls.DataGridTemplateColumn'.'IsVisible': 'Null value in expression '{empty}' at ''.' (DataGridTemplateColumn #54330728)
[3/9/2022 6:57:18 PM][Debug][MainWindow.CheckForModUpdates: Line 1011] Attempting to check for mod updates via cache
[3/9/2022 6:57:18 PM][Alert][MainWindow.CheckForModUpdates: Line 1183] Failed to get mod updates via smapi.io: System.IO.FileNotFoundException: C:\XboxGames\Stardew Valley\Content\StardewModdingAPI.exe
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at Stardrop.Views.MainWindow.CheckForModUpdates(List`1 mods, Boolean useCache, Boolean probe, Boolean skipCacheCheck)
[3/9/2022 6:57:40 PM][Debug][SettingsWindow..ctor: Line 54] Loaded theme Dark
[3/9/2022 6:57:40 PM][Debug][SettingsWindow..ctor: Line 54] Loaded theme Light
[3/9/2022 6:57:40 PM][Debug][SettingsWindow..ctor: Line 54] Loaded theme Solarized-Lite
[3/9/2022 6:57:40 PM][Debug][SettingsWindow..ctor: Line 54] Loaded theme Stardrop
`

**Comment by Verciv** [comment]
Never mind, I seem to have found a workaround:

- Create 2 copies of SMAPI, name one Stardew Valley.exe and the other StardewModdingAPI.exe, and have Stardrop link to the latter.
- Game _should_ launch normally, but I am not sure.
