### ISSUE TITLE
Stardrop wont open

### ISSUE THREAD

**Issue by Kleidoxon** [Floogen/Stardrop#92]
i dnt know what happen after i close the app then i try to open it just loading then stop nothing happened. i already restart, delete and download again nothing happen. My stardrop wont open. Its weirdd. What is happening.

this is last log 17 Jul 4.18 AM

[17-Jul-22 4:18:58 AM][Debug][Program.Main: Line 73] 
-- Startup Data --
Time: 17-Jul-22 4:18:58 AM
OS: [Windows] Microsoft Windows 10.0.18362
Settings Directory: C:\Users\i5\AppData\Roaming\Stardrop\Data
Active Directory: C:\Users\i5\Downloads\Stardrop-win-x64\Stardrop
Version: 1.0.0-beta.33
----------------------

[17-Jul-22 4:18:58 AM][Debug][Program.Main: Line 74] Started with the following arguments: 
[17-Jul-22 4:18:58 AM][Debug][Translation.LoadTranslations: Line 120] Loaded language de
[17-Jul-22 4:18:58 AM][Debug][Translation.LoadTranslations: Line 120] Loaded language default
[17-Jul-22 4:18:58 AM][Debug][Translation.LoadTranslations: Line 120] Loaded language es
[17-Jul-22 4:18:58 AM][Debug][Translation.LoadTranslations: Line 120] Loaded language fr
[17-Jul-22 4:18:58 AM][Debug][Translation.LoadTranslations: Line 120] Loaded language it
[17-Jul-22 4:18:58 AM][Debug][Translation.LoadTranslations: Line 120] Loaded language pt
[17-Jul-22 4:18:58 AM][Debug][Translation.LoadTranslations: Line 120] Loaded language ru
[17-Jul-22 4:18:58 AM][Debug][Translation.LoadTranslations: Line 120] Loaded language th
[17-Jul-22 4:18:58 AM][Debug][Translation.LoadTranslations: Line 120] Loaded language tr
[17-Jul-22 4:18:58 AM][Debug][Translation.LoadTranslations: Line 120] Loaded language uk
[17-Jul-22 4:18:58 AM][Debug][Translation.LoadTranslations: Line 120] Loaded language zh
[OpenGL] Unable to initialize EGL-based rendering: 'System.DllNotFoundException: Dll was not found.
   at Avalonia.OpenGL.Angle.AngleEglInterface.EGL_GetProcAddress(String proc)
   at Avalonia.OpenGL.Angle.AngleEglInterface.LoadAngle()
   at Avalonia.OpenGL.Angle.AngleEglInterface..ctor()
   at Avalonia.OpenGL.Angle.AngleWin32EglDisplay..ctor()
   at Avalonia.Win32.Win32GlManager.<>c.<Initialize>b__0_1()
   at Avalonia.OpenGL.Egl.EglPlatformOpenGlInterface.TryCreate(Func`1 displayFactory)'
LogHost: Initializing to normal mode (.cctor)
[17-Jul-22 4:19:00 AM][Debug][Translation.LoadTranslations: Line 120] Loaded language de
[17-Jul-22 4:19:00 AM][Debug][Translation.LoadTranslations: Line 120] Loaded language default
[17-Jul-22 4:19:00 AM][Debug][Translation.LoadTranslations: Line 120] Loaded language es
[17-Jul-22 4:19:00 AM][Debug][Translation.LoadTranslations: Line 120] Loaded language fr
[17-Jul-22 4:19:00 AM][Debug][Translation.LoadTranslations: Line 120] Loaded language it
[17-Jul-22 4:19:00 AM][Debug][Translation.LoadTranslations: Line 120] Loaded language pt
[17-Jul-22 4:19:00 AM][Debug][Translation.LoadTranslations: Line 120] Loaded language ru
[17-Jul-22 4:19:00 AM][Debug][Translation.LoadTranslations: Line 120] Loaded language th
[17-Jul-22 4:19:00 AM][Debug][Translation.LoadTranslations: Line 120] Loaded language tr
[17-Jul-22 4:19:00 AM][Debug][Translation.LoadTranslations: Line 120] Loaded language uk
[17-Jul-22 4:19:00 AM][Debug][Translation.LoadTranslations: Line 120] Loaded language zh
[17-Jul-22 4:19:01 AM][Debug][App.Initialize: Line 41] Loaded theme Dark
[17-Jul-22 4:19:01 AM][Debug][App.Initialize: Line 41] Loaded theme Light
[17-Jul-22 4:19:01 AM][Debug][App.Initialize: Line 41] Loaded theme Solarized-Lite
[17-Jul-22 4:19:01 AM][Debug][App.Initialize: Line 41] Loaded theme Stardrop
[Binding] Error in binding to 'Avalonia.Controls.NativeMenuItem'.'Command': 'Null value in expression '{empty}' at ''.' (NativeMenuItem #17102575)
[Binding] Error in binding to 'Avalonia.Controls.DataGridTemplateColumn'.'IsVisible': 'Null value in expression '{empty}' at ''.' (DataGridTemplateColumn #41270904)
[Binding] Error in binding to 'Avalonia.Controls.DataGridTemplateColumn'.'IsVisible': 'Null value in expression '{empty}' at ''.' (DataGridTemplateColumn #23656219)
[Binding] Error in binding to 'Avalonia.Controls.DataGridTemplateColumn'.'IsVisible': 'Null value in expression '{empty}' at ''.' (DataGridTemplateColumn #53163272)
[17-Jul-22 4:19:02 AM][Alert][Program.Main: Line 143] System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\gamesss\steamapps\common\Stardew Valley\Mods\Stardrop Installed Mods\[CP] CL's Haley'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1.DelegateEnumerator..ctor(FileSystemEnumerable`1 enumerable, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerable`1.GetEnumerator()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at Stardrop.ViewModels.MainWindowViewModel.GetManifestFiles(DirectoryInfo modDirectory)
   at Stardrop.ViewModels.MainWindowViewModel.GetManifestFiles(DirectoryInfo modDirectory)
   at Stardrop.ViewModels.MainWindowViewModel.DiscoverMods(String modsFilePath)
   at Stardrop.ViewModels.MainWindowViewModel..ctor(String modsFilePath, String version)
   at Stardrop.Views.MainWindow..ctor()
   at Stardrop.App.OnFrameworkInitializationCompleted()
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at Stardrop.Program.Main(String[] args)

[log.txt](https://github.com/Floogen/Stardrop/files/9126613/log.txt)

**Comment by Floogen** [comment]
Fixed with Stardrop v1.0.0-beta.34. This was due to the mod (CL's Haley) having a malformed folder within the zip, specifically it had an unhandled space at the end of the folder name.

You will need to delete the old "[CP] CL's Haley " folder before reinstalling the mod, though you may have difficulties doing so via Windows.

To clear that malformed mod, you will need to clear out the contents of the "[CP] CL's Haley " folder (the one with a space at the end of its name). You will then want to copy the folders path and execute the follow command in CMD:
`rd "\\?\PATH_TO_MALFORMED_FOLDER\[CP] CL's Haley "`
