### ISSUE TITLE
can't get stardrop to open

### ISSUE THREAD

**Issue by rosevicee** [Floogen/Stardrop#99]
It used to work, then stopped one day.  Deleted the app and downloaded and installed it again. Did not work either, now half year later I installed latest version, still not launching.
What can I do?

[7-9-2022 15:49:39][Debug][Program.Main: Line 73] 
-- Startup Data --
Time: 7-9-2022 15:49:39
OS: [Windows] Microsoft Windows 10.0.19042
Settings Directory: C:\Users\User\AppData\Roaming\Stardrop\Data
Active Directory: C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Stardrop - Windows-10455-1-0-0-beta-34-1659058616\Stardrop
Version: 1.0.0-beta.34
----------------------

[7-9-2022 15:49:39][Debug][Program.Main: Line 74] Started with the following arguments: 
[7-9-2022 15:49:39][Alert][Program.Main: Line 143] System.Text.Json.JsonException: '0x00' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '0x00' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Stardrop.Program.Main(String[] args)

**Comment by ImaanBontle** [comment]
@rosevicee This is almost the exact error I had. Have you checked the settings.json file? It may be corrupted. Deleting it fixed things for me (don't worry, doesn't affect your mods or profiles).

**Comment by Floogen** [comment]
This should be resolved with v1.0.0-beta.37. If it is not, please do let me know.

**Comment by feaghacu** [comment]
I am experiencing tha same problem with the latest update. It does open if i delete the .json file, but immediately reverts once i configure the SMaPI route. Is there a solution so far?

**Comment by Floogen** [comment]
Please send over your Stardrop log file, per the instructions [found here](https://floogen.gitbook.io/stardrop/resources/reporting-issues). I am unable to help further without it.

**Comment by feaghacu** [comment]
[log.txt](https://github.com/Floogen/Stardrop/files/11470366/log.txt)
 https://smapi.io/log/13eda9ab88bf47bebf62201c54414aff
Thanks for the help, apologies for not reading the instructions properly
